sudo: false
language: go
go:
  - "1.9"
  - "1.10"
  - "tip"
os:
  - linux
  - osx
go_import_path: github.com/supermercato24/colander
script:
  - go test -race -v ./...
notifications:
  email:
    on_success: never
